runtime: python27
api_version: 1
threadsafe: true
automatic_scaling:
  max_idle_instances: 2 
  
handlers:

# - url: /customtask/.*
#   script: taskutils.app
#   login: admin
  
- url: /.*
  script: main.app
  login: admin
  